### PR TITLE
Update .env

### PR DESCRIPTION
**Pull request by katosdev**
Remove hardcoded SMTP details and adjust image to new directory: https://git.homebox.software/

### CODE REVIEW

**Comment by katosdev** [comment]
Any reason this was closed without comment, sorry? 🙂 

just trying to work out how I can better contribute in the future

**Comment by heyvaldemar** [comment]
> Any reason this was closed without comment, sorry? 🙂
> 
> just trying to work out how I can better contribute in the future

hey @katosdev, thanks for contributing! I just wanted to test this new image locally. It’s all set now, and I’ll update the `.env` file with the new image URL but will keep the other variables unchanged.

**Comment by katosdev** [comment]
> > Any reason this was closed without comment, sorry? 🙂
> > just trying to work out how I can better contribute in the future
> 
> hey @katosdev, thanks for contributing! I just wanted to test this new image locally. It’s all set now, and I’ll update the `.env` file with the new image URL but will keep the other variables unchanged.

Honestly surprised that the PR was closed without any acknowledgement, I’m also curious why the variables are being left in? These appear to expose potential data and should probably be adjusted to generic placeholders?

**Comment by heyvaldemar** [comment]
> Honestly surprised that the PR was closed without any acknowledgement

Man, come on, do you really expect every PR to get a royal trumpet announcement? 😄 I didn’t mean to overlook your efforts—I got to it as soon as I tested the image. When I closed the PR, it was simply because the testing phase was complete, not because I was ignoring your suggestions.

> I’m also curious why the variables are being left in? These appear to expose potential data and should probably be adjusted to generic placeholders?

As for the variables, they’re filled with non-existent accounts and passwords. I left them in to make the setup clearer and easier, especially for newbies who might not be familiar with what to input. It’s all about making it straightforward, not about exposing any real data.

**Pull request closed without merging**
